export const CAMBIAR_URL = "CAMBIAR_URL";
export const SET_URL_BATCH = "SET_URL_BATCH";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const SET_CLIENT_ID_ANALYTICS = "SET_CLIENT_ID_ANALYTICS";
export const SET_ENVIRONMENT_HOMO = "SET_ENVIRONMENT_HOMO";



