export const SET_VALUE_INF_OBL = "SET_VALUE_INF_OBL";
export const SET_VALUE_INF_PER = "SET_VALUE_INF_PER";
export const SET_VALUE_INF_PER_CONYUGE = "SET_VALUE_INF_PER_CONYUGE";
export const SET_VALUE_DOMICILIO = "SET_VALUE_DOMICILIO";
export const SET_VALUE_FORM_ENT = "SET_VALUE_FORM_ENT";
export const SET_CUIL_DATOS_PERSONALES = "SET_CUIL_DATOS_PERSONALES";
export const SET_CIUDADES = "SET_CIUDADES";
export const SET_CUIL_CONYUGE = "SET_CUIL_CONYUGE";
export const SET_LOCALIDADES_DOMICILIO = "SET_LOCALIDADES_DOMICILIO";
export const SET_LOCALIDADES_NUEVO_DOMICILIO = "SET_LOCALIDADES_NUEVO_DOMICILIO";
export const SET_SUCURSAL = "SET_SUCURSAL";
export const SET_NUEVO_DOMICILIO = "SET_NUEVO_DOMICILIO";
export const SET_IS_EXTRANJERO = "SET_IS_EXTRANJERO";










